### ISSUE TITLE
A and D not activating at all

### ISSUE THREAD

**Issue by MoxxieSoda** [cafali/SnapKey#13]
I tried switching the numbers in the config and everything but it just refuses to do anything I open the **.exe** and opening it in administrator mode as well

I am using a Razer Huntsman Mini white, if that helps with any info

**Comment by cafali** [comment]
Did that issue occur after changing the parameters in the cfg file? Since A and D are set up as the default keys in the cfg file:

keyA=**65**
keyD=**68**

Make sure you adjust the values based on the ASCII table provided in the configuration file. 

If that doesn’t work, please **[download the vanilla config.cfg](https://github.com/cafali/SnapKey/blob/main/config.cfg)** file again from the repository and replace the existing file in the main SnapKey directory.

You can also test it online to see if it works for you here:

https://drakeirving.github.io/MultiKeyDisplay/

**Comment by cafali** [comment]
Also, check out the guide on how to properly rebind keys using the config file:

[Rebinding Keys](https://github.com/cafali/SnapKey?tab=readme-ov-file#rebind-keys)
