### ISSUE TITLE
bannable?

### ISSUE THREAD

**Issue by MrBoringCom** [cafali/SnapKey#5]
I was wondering if using this program is bannable. Am I allowed to use this in valve mm and faceit?

**Comment by Kwisss** [comment]
Had no issues with faceit, it is fine for now until publish news its not.
Moreover this code does not jiggle like in the Wooting video, but I think they are working on it.

**Comment by cafali** [comment]
The code provided does not engage with any game files.
When it comes to online games, I cant really anwser this question for you.
Its the first time ever we got a feature like that in modern keyboards.
Platforms like faceit & others will need to give a statement about this feature since, it will become more popular in the future also by other keyboard brands.

**Comment by Dillacorn** [comment]
At the moment I don't believe using this program would be bannable given its popularity.. BUT It could def be bannable in the future if the devs for the game you're playing flag with there preferred anti-cheat solution. For example you can run a .ahk with AutoHotkey that has no interaction with Apex Legends but people have reportedly been banned without question because Apex's EAC has specific applications it looks for running on your system and AutoHotkey is prohibited. It's very dumb... Maybe just change the .exe name to something else in hopes that EAC or other anti-cheat clients won't flag your account.
