### ISSUE TITLE
Rainbow Six Siege - Holding one strafe key (A) then clicking the opposite spams a lot of unbound keypresses specifically Tab, PageUp, - or _, Enter and the first pressed key

### ISSUE THREAD

**Issue by KarambwanaKodou** [cafali/SnapKey#51]
Game is Rainbow Six Siege
Here is my evidence: https://imgur.com/a/dOdJkvH

**Comment by minteeaa** [comment]
R6S is [marked as incompatible](https://github.com/cafali/SnapKey/wiki/Compatibility-List), this could potentially be the game's anti-cheat interaction with the detection of this "rapid keypress" tech

i don't speak on the main repository's status of research into this issue; but keep up to date with the [discussions](https://github.com/cafali/SnapKey/discussions) to see potential updates that resolve this issue

**Comment by cafali** [comment]
What version of SnapKey have you been using? Have you tried the latest version yet? Ubisoft uses many different custom game engines, so I’m interested in knowing if it functions correctly now after the scancode handling update, which added compatibility with many other games like Apex and COD.

https://github.com/cafali/SnapKey/releases

pls test the new version, if possible, and give me a status on whether it works or not. 
Since Rainbow Six is still marked as 'not compatible,' I would like to know how it functions after the update.

**Comment by KarambwanaKodou** [comment]
I'm testing it right now and it looks like you have fixed the issue with R6S!!!

Thank you so so much

my hall effect keyboard still hasn't implemented a SOCD function so i'm left with using this or HID Remapper but I don't have an RP2040 board lol
